services:
  postgres:
    image: postgres:17
    restart: unless-stopped
    container_name: postgres

    env_file:
      - .env

    volumes:
      - postgres_data:/var/lib/postgresql/data

    networks:
      - homelab

  adminer:
    image: adminer
    container_name: adminer
    restart: unless-stopped
    ports:
      - "8081:8080"

volumes:
  postgres_data:

networks:
  homelab:
    external: true
