services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    ports:
      - "8080:80"
    volumes:
      - /home/domel:/srv
      - /media/domel/Gry-i-Programy:/srv/games
      - ./database.db:/database.db
      - ./settings.json:/.filebrowser.json
    restart: unless-stopped
