services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    environment:
      HOMEPAGE_ALLOWED_HOSTS: 100.121.236.113:3000, localhost:3000
    ports:
      - "3000:3000"
    volumes:
      - ./config:/app/config
