services:
  uptime-kuma:
    image: louislam/uptime-kuma
    container_name: uptimekuma
    restart: unless-stopped
    volumes:
      - uptimekuma_data:/app/data
    ports:
      - "3001:3001"
volumes:
  uptimekuma_data:
