# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/

- Infrastructure:
    - Portainer:
        href: https://portainer.lab/
        description: Container management

    - Uptime Kuma:
        href: http://uptimekuma.lab/
        description: Service monitoring

    - Nginx Proxy Manager:
        href: http://nginxproxymanager.lab/
        description: Proxy management

    - AdGuard Home:
        href: http://adguard.lab/
        description: DNS management

    - Adminer:
        href: http://adminer.lab/
        description: PostgreSQL administration

- Storage:
    - FileBrowser:
        href: http://filebrowser.lab/
        description: Files management

    - Nextcloud:
        href: http://nextcloud.lab/
        description: Personal cloud storage
